version: '3.8'

services:
  fastapi:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ${ECR_IMAGE_REPO}
    container_name: fastapi_app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - REDIS_URL=${REDIS_URL}
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
