version: '3.8'

services:
  fastapi:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ashishkingdom/ci-cd-python-redis:latest
    container_name: fastapi_app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - REDIS_URL=redis://redis:6379
    networks:
      - app_network

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
