version: '3.8'

services:
  fastapi:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ${ECR_IMAGE_REPO}
    container_name: fastapi_app
    environment:
      - name=value
    ports:
      - "8000:8000"


